name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to publish (e.g., v0.1.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if draft release exists
        id: check-draft
        run: |
          # Check if the specified version exists and is a draft
          if ! gh release view "${{ github.event.inputs.version }}" --json isDraft --jq '.isDraft' 2>/dev/null | grep -q true; then
            echo "Error: Draft release ${{ github.event.inputs.version }} not found or not a draft"
            echo "Available draft releases:"
            gh release list --limit 100 | grep "Draft" || echo "No draft releases found"
            exit 1
          fi

          echo "Found draft release: ${{ github.event.inputs.version }}"
          echo "draft_found=true" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release with Release Drafter
        if: steps.check-draft.outputs.draft_found == 'true'
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.event.inputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
