name: Update Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-draft:
    name: Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    needs:
      - release-draft
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            output: simple-cli-${{ needs.release-draft.outputs.tag_name }}-linux-amd64
          - os: darwin
            arch: arm64
            output: simple-cli-${{ needs.release-draft.outputs.tag_name }}-darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ${{ matrix.output }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  upload-binaries:
    name: Upload Binaries
    needs:
      - build
      - release-draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload binaries to Release Draft
        run: |
          gh release upload ${{ needs.release-draft.outputs.tag_name }} ./artifacts/simple-cli-${{ needs.release-draft.outputs.tag_name }}-linux-amd64/simple-cli-${{ needs.release-draft.outputs.tag_name }}-linux-amd64 --clobber
          gh release upload ${{ needs.release-draft.outputs.tag_name }} ./artifacts/simple-cli-${{ needs.release-draft.outputs.tag_name }}-darwin-arm64/simple-cli-${{ needs.release-draft.outputs.tag_name }}-darwin-arm64 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
